version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: gentle-db
    env_file:
      - ./.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./db/db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - gentle-networks

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gentle-api
    env_file:
      - ./.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - OPENAI_AZURE_ENDPOINT=${OPENAI_AZURE_ENDPOINT}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    networks:
      - gentle-networks

networks:
  gentle-networks:
    driver: bridge
 
