version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: gentle-db
    env_file:
      - ./env/.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./db/db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
